[project]
name = "cellshift"
description = "XLSX based contract files change year to year at the City of Memphis Department of Public Works. An existing 2025 contract spreadsheet can be easily cast to a 2026 contract spreadsheet using cellshift."
readme = "README.md"
dependencies = [
    "dworshak-config>=0.2.8",
    "openpyxl>=3.1.5",
    "pyhabitat>=1.3.9",
    "typer>=0.27.0",
    "typer-helptree>=0.2.11",
]

dynamic = ["version"]
license = "null" # not yet
requires-python = ">=3.9,<3.15"
authors = [
    { name = "George Clayton Bennett", email = "george.bennett@memphistn.gov" },
    { name = "Ranisha Lomax", email = "ranisha.lomax@memphistn.gov" }
]
maintainers = [
    { name = "George Clayton Bennett", email = "george.bennett@memphistn.gov" },
    { name = "Ranisha Lomax", email = "ranisha.lomax@memphistn.gov" }
]
