name: Build AppImage

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  appimage:
    # Explicitly grant write access so the called reusable workflow can inherit it
    permissions:
      contents: write
    uses: City-of-Memphis-Wastewater/maxson-build-utils/.github/workflows/reusable-appimage.yml@main
    with:
      build_script: "scripts/build_executable.py"
      #app_dir: "dist/onedir/cellshift"
      exe_name: "cellshift"
      pretty_name: "CellShift"
      icon_path: "src/cellshift/data/icons/placeholder_1024x1024.png"
