name: Build Flatpak

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  flatpak:
    permissions:
      contents: write
    uses: City-of-Memphis-Wastewater/maxson-build-utils/.github/workflows/reusable-flatpak.yml@main
    with:
      desktop_path: "packaging/flatpak/io.github.city_of_memphis_wastewater.cellshift.desktop"
      metainfo_path: "packaging/flatpak/io.github.city_of_memphis_wastewater.cellshift.metainfo.xml"
      manifest_path: "packaging/flatpak/io.github.city_of_memphis_wastewater.cellshift.yaml"
      app_id: "io.github.city_of_memphis_wastewater.cellshift"
      app_name: "cellshift"
